-- Staging Schema v0 — Solar 260312
-- 草案のみ。実行禁止。
-- Generated: 2026-04-06

-- 顧客基本情報。マスタ行（お客様IDあり）から抽出。
CREATE TABLE staging_customer (
  customer_id TEXT NOT NULL,
  furigana TEXT,
  address TEXT,
  postal_code TEXT,
  phone TEXT,
  phone_search TEXT,
  fax TEXT,
  email TEXT,
  representative_furigana TEXT,
  representative_mobile TEXT,
  representative_birthday DATE,
  contact_furigana TEXT,
  contact_mobile TEXT,
  emergency_contact TEXT,
  occupation TEXT,
  industry_subclass TEXT,
  fm_password TEXT,
  fm_username TEXT,
  invoice_registration TEXT,
  application_id TEXT,
  contact_info TEXT,
  preferred_contact_time TEXT,
  raw_source_file TEXT NOT NULL,
  raw_row_origin INTEGER NOT NULL,
  source_fingerprint TEXT NOT NULL
);

-- 案件・契約情報。マスタ行から抽出。customer と 1:1 の可能性が高いが未確定。
CREATE TABLE staging_deal (
  customer_id TEXT NOT NULL,
  status TEXT,
  cancel_flag TEXT,
  cancel_date DATE,
  cancel_reason TEXT,
  estimate_maker TEXT,
  estimate_request_date DATE,
  estimate_arrival_date DATE,
  estimate_note TEXT,
  fit_approval_date DATE,
  fit_application_date DATE,
  maker TEXT,
  module TEXT,
  installed_kw NUMERIC(10,3),
  installation_store TEXT,
  installation_address TEXT,
  installation_phone TEXT,
  installation_fax TEXT,
  building_age INTEGER,
  order_date DATE,
  estimate_request_date_2 DATE,
  estimate_arrival_date_2 DATE,
  site_survey_date DATE,
  applicant TEXT,
  application_send_date DATE,
  lease_certificate_send DATE,
  consent_send DATE,
  contractor TEXT,
  contractor_relationship TEXT,
  user_relationship TEXT,
  monthly_amount NUMERIC(15,2),
  lease_fee NUMERIC(15,2),
  credit_company TEXT,
  credit_request_date DATE,
  credit_result TEXT,
  credit_result_date DATE,
  credit_company_2 TEXT,
  power_application_date DATE,
  power_approval_date DATE,
  drone_survey_date DATE,
  construction_request TEXT,
  construction_request_2 TEXT,
  construction_date DATE,
  construction_complete_date DATE,
  revisit_date DATE,
  completion_report DATE,
  confirmation_complete_date DATE,
  report_arrival_date DATE,
  floor_plan_arrival DATE,
  warranty_application DATE,
  warranty_arrival DATE,
  disaster_insurance_application DATE,
  disaster_insurance_arrival DATE,
  invoice_date DATE,
  invoice_date_2 DATE,
  payment_date DATE,
  payment_date_2 DATE,
  delivery_date DATE,
  order_placement_date DATE,
  accounting_month TEXT,
  accounting_date DATE,
  gross_profit NUMERIC(15,2),
  service_item_count INTEGER,
  service_item_price NUMERIC(15,2),
  service_item_cost NUMERIC(15,2),
  service_item_delivery DATE,
  material TEXT,
  material_count INTEGER,
  material_unit_price NUMERIC(15,2),
  material_cost NUMERIC(15,2),
  material_name TEXT,
  construction_management TEXT,
  sales_channel TEXT,
  sales_store TEXT,
  slip_number TEXT,
  additional_construction TEXT,
  required_documents TEXT,
  required_documents_date DATE,
  note TEXT,
  caution TEXT,
  sheet_count INTEGER,
  mail_date DATE,
  grid_connection_date DATE,
  appointment_staff TEXT,
  sales_staff TEXT,
  sales_comment TEXT,
  visit_count INTEGER,
  visit_staff TEXT,
  raw_source_file TEXT NOT NULL,
  raw_row_origin INTEGER NOT NULL,
  source_fingerprint TEXT NOT NULL
);

-- コール履歴。Source A (独立コール履歴 XLSX) と Source B (顧客ファイル内ポータル展開) の2系統。
CREATE TABLE staging_activity_call (
  source_kind TEXT NOT NULL,
  call_date DATE,
  call_time TIME,
  call_staff TEXT,
  content TEXT,
  customer_staff TEXT,
  raw_phone TEXT,
  normalized_phone TEXT,
  matched_customer_id TEXT,
  matched_customer_candidate_count INTEGER,
  match_type TEXT,
  fill_forward_customer_id TEXT,
  raw_source_file TEXT NOT NULL,
  raw_row_origin INTEGER NOT NULL,
  source_fingerprint TEXT NOT NULL
);
